name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    steps:
    - name: install 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    

      
    

